server:
  port: 8020

spring:
  application:
    name: bin‐order #微服务名称
  cloud:
    nacos:
      discovery:
        server‐addr: localhost:8848
        namespace: dev
  datasource:
    username: root
    password: 82858541zyyT
    url: jdbc:mysql://localhost:3306/cloud_order?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



